### ISSUE TITLE
would appreciate a "Delete" icon on each bookmark

### ISSUE THREAD

**Issue by goofy-mdn** [flusio/flusio#182]
une icône poubelle m'a manqué quand j'ai voulu supprimer un signet. Passer d'abord par "modifier" est un peu bizarre pour moi.
![Screenshot_2021-02-07 digital privacy](https://user-images.githubusercontent.com/41866949/107150344-a1a8c780-695d-11eb-8d67-f2ea1d5e9951.png)

**Comment by marienfressinaud** [comment]
Coucou @goofy-mdn ! J'ai pris en compte ton retour de manière un peu différente : il y a désormais une option "Marquer comme lu" dans le menu secondaire, ce qui permet de retirer des signets non pas en un clic, mais en deux ;) N'hésite pas à me dire si ça ne correspond pas à ce que tu cherchais.

**Comment by bepolymathe** [comment]
Pourquoi faire en deux clics ce qu’on peut faire en un ?

**Comment by marienfressinaud** [comment]
En fait c'était le cas avant, sauf que ça posait des problèmes d'utilisabilité. Ça facilitait certes le retrait, mais aussi les erreurs : il fallait donc prendre en compte l'annulation de l'action et c'était pas forcément très clair.

D'autre part, le workflow principal consiste à faire passer les signets dans le journal, depuis lequel on peut marquer comme lu.

**Comment by bepolymathe** [comment]
> D'autre part, le workflow principal consiste à faire passer les signets dans le journal, depuis lequel on peut marquer comme lu.

Je pense que c’est l’idée que tu avais en tête au départ, à partir de laquelle tu sembles avoir construit le projet. Mais l’arrivée des flux RSS change la donne de mon point de vue. Ça veut dire que j’utilise flusio pour faire de la veille et de l’archivage de lecture. Pour la veille, la fonctionnalité que j’utilise le plus est "les dernières publications" et je balaie les dernières publications. Quand on a beaucoup de flux c’est fastidieux de devoir cliquer 2 fois (et sur plusieurs pages de 9 entrées).

**Comment by marienfressinaud** [comment]
Alors j'ai considéré que la question initiale portait spécifiquement sur la page des signets, pour laquelle l'action en deux clics me semble poser moins de soucis. Par contre j'entends que ce soit fastidieux au sein du journal et ici c'est plus gênant ! Est-ce que tu retires les liens 1 par 1 ou tu utilises le bouton "Vider le journal" ?

**Comment by bepolymathe** [comment]
En fait, je parcours du regard les 9 entrées. Si aucune n’est à lire plus tard ou à conserver, je fais "vider le journal", puis j’actualise pour avoir les 9 suivants. Si une ou deux entrées mérites d’être lu plus, je les ajoute et je fais "vider le journal" après.
