### ISSUE TITLE
Ma connexion Internet de campagne m'empêche d'utiliser l'app tant que les icônes ne sont pas chargées

### ISSUE THREAD

**Issue by oncletom** [flusio/flusio#227]
Ça m'arrive de regarder cet écran pendant 15 secondes avant de repérer les zones cliquables : 

![image](https://user-images.githubusercontent.com/138627/114763714-682c7800-9d63-11eb-9846-1a400b300796.png)

Si jamais je suis aventureux : 

![image](https://user-images.githubusercontent.com/138627/114763965-b0e43100-9d63-11eb-80e9-b3753f3651c0.png)

Le fait que le chargement de l'icon font ne soit pas priorisé crée ce problème (diagnostic à vue de pif).

**Comment by marienfressinaud** [comment]
15 secondes, c'est long ! :/ En principe il y a du cache pendant 30 jours, donc ça ne devrait pas être si fréquent, tu confirmes ?

Le problème (technique) est un poil plus complexe car il ne s'agit pas d'un unique fichier "font" : les icônes sont sous forme [de SVG](https://github.com/flusio/flusio/tree/main/src/assets/icons) et sont intégrées [une à une](https://github.com/flusio/flusio/blob/main/src/assets/stylesheets/_icons.css#L78-L218) en CSS.

Une alternative possible qui pourrait résoudre le problème (mais demande des changements assez importants) serait d'intégrer les icônes SVG directement dans le HTML. Je perdrais par contre le bénéfice du cache. Il y aurait la possibilité d'utiliser des [références externes](https://css-tricks.com/svg-use-with-external-reference-take-2/), mais ce n'est pas si simple. L'injection dans le HTML semble être la meilleure solution aujourd'hui. C'est ce que fait GitHub au final, le cache n'est peut-être pas un si gros problème :) Reste le coût technique à changer l'existant, peut-être pas énorme, mais prise de tête. Je calerais ça un de ces jours !

**Comment by oncletom** [comment]
Ou plus simple : 

```patch
.icon--credit-card::before {
-    background-image: url("../icons/commerce/credit-card-line.svg");
+    background-image: url(data:image/svg+xml;base64,…);
}
```

**Comment by marienfressinaud** [comment]
Oui effectivement je n'y avais pas pensé, bonne idée ! :+1: Ceci dit une raison non évoquée dans mon précédent message pour passer à une injection dans le HTML serait aussi de pouvoir me passer [d'un hack rigolo mais pas très maintenable](https://github.com/flusio/flusio/blob/main/src/assets/stylesheets/_icons.css#L35-L47) (i.e. je pourrais utiliser `fill` à la place).

Ça me donne quand même une solution intermédiaire.

**Comment by marienfressinaud** [comment]
J'ai pris le temps de changer le système cette après-midi, c’était un peu rébarbatif mais moins pénible que ce que je craignais. J'ai opté pour intégrer les SVG directement dans le HTML, donc normalement plus aucun délais entre l'affichage de l'interface et le chargement des icônes. Ça m’a aussi permis de faire sauter tous les petits hacks liés aux icônes \o/

Ceci dit les pages HTML sont maintenant plus grosses : +53% sur un journal relativement chargé (passage de ~165 Ko à ~253 Ko). C’est plus léger sur les autres pages qui font moins appel aux icônes. Je pense qu'il y aura une phase d'optimisation dans un second temps.

Je pense que ça passera en prod' la semaine prochaine.

**Comment by marienfressinaud** [comment]
C'est en prod ! :)
