### ISSUE TITLE
Horodatage

### ISSUE THREAD

**Issue by bepolymathe** [flusio/flusio#308]
Salut, 

De mon point de vue, la date du jour n’est pas assez précise dans les vignettes. 

![image](https://user-images.githubusercontent.com/29939805/121662187-520e1000-caa5-11eb-9c05-543ed4770948.png)

Si par exemple j’ajoute le flux rss de commentaires de blog (linuxFR au hasard), je voudrais pouvoir voir les heures précises des commentaires en question. Idem pour les articles de presse. La date du jour est trop imprécise.

**Comment by marienfressinaud** [comment]
J'entends et je comprends le besoin qu'il peut y avoir ici concernant les commentaires. Pour les articles de presse, j'ai le sentiment que la plupart du temps on n'est pas à quelques heures près. Ça rejoint aussi mon commentaire sur LinuxFr dans lequel je te disais que flusio n'est pas un outil adapté pour faire de la veille "temps réel", ce n'est pas sa philosophie.

Mon avis n'est pas franchement tranché sur la question, mais j'aimerais savoir si c'est un besoin généralisé avant de m'y atteler. Une solution pourrait être d'avoir l'heure au survol : ça aurait l'avantage de ne pas surcharger l'interface tout en gardant l'info accessible.

**Comment by bepolymathe** [comment]
> Ça rejoint aussi mon commentaire sur LinuxFr dans lequel je te disais que flusio n'est pas un outil adapté pour faire de la veille "temps réel", ce n'est pas sa philosophie.

De mon point de vue tu devrais assouplir ta position sur ce point. L’intérêt principal de flusio pour moi et de proposer de combiner la sauvegarde de signet avec la lecture de flux RSS. Je pense que c’est l’intérêt identifié par pas mal d’utilisateurs, notamment pour un usage professionnel. C’est pour cela qu’on cherche le meilleur des deux mondes. D’où les demandes sur un outil de recherche, un jeu de tags, un horodatage précis, etc.

**Comment by marienfressinaud** [comment]
> L’intérêt principal de flusio pour moi et de proposer de combiner la sauvegarde de signet avec la lecture de flux RSS.

Alors là je suis en désaccord avec toi. Le problème principal que j'ai identifié (en en discutant avec différentes personnes avant et pendant la conception de flusio) est la surcharge d'information : c’est ça le cœur de flusio ! Et j'ai identifié le temps réel comme un facteur influant sur cette surcharge d'information car on se voit imposer le rythme de publication des publieurs. On peut discuter s'il n'y a pas moyen de gérer le temps réel sans être surchargé, par contre ça ne se fera pas si cela doit générer de l'inconfort.

Dans ce contexte, je ne suis pas opposé à l'affichage de l'heure puisqu'à priori elle te permettrait d'être plus serein. Par contre je crains la surcharge d'information pour une demande qui me semble principalement guidée par une habitude du "temps réel" (et je peux me tromper !) Bref, l'info au survol me semble un bon compromis :)

Concernant ma position sur le moteur de recherche et les tags, c'est un sujet différent qui consiste essentiellement à dire que je réfléchis en terme de problèmes rencontrés et pas en terme de solution technique. J'ai identifié le besoin concernant les tags, mais moins bien cerné celui pour le moteur de recherche (principalement parce qu'on m'a fait moins de retours dessus, et parce que j'ai passé moins de temps à y réfléchir hein :)). Bref : c'est bien prévu, mais après d'autres choses qui me paraissent aujourd'hui plus importantes !

**Comment by numahell** [comment]
Attention, la date affichée c'est bien celle de sauvegarde du signet, pas celle de publication de l'article ou du commentaire ?

**Comment by marienfressinaud** [comment]
La date est celle de la sauvegarde oui, sauf dans le cas des flux où il s'agit de la date de publication (mais si on considère un flux comme une collection extérieure, il s'agit de la date de sauvegarde dans cette "collection")

**Comment by marienfressinaud** [comment]
L'heure est maintenant affichée au survol !
