### ISSUE TITLE
S'affranchir de la limite de 3 jours dans les news provenant des collections

### ISSUE THREAD

**Issue by oncletom** [flusio/flusio#310]
Je passe à côté de pleins d'items parce qu'il y a une limite arbitraire de 3 jours par rapport à la date de publication d'un item (pas dite, pas explicite).

Ça a pour effet que je me rends sur flus plus souvent, pour remplir mes news et éviter d'en "perdre" (parce que la vue collection ne m'offre aucun moyen de voir les collections qui ont des nouveaux trucs — ce qui fait que je ne me rends jamais dans cet onglet là).

**Comment by marienfressinaud** [comment]
Oui, la version actuelle est plus un entre-deux des solutions que j'avais à ma disposition. C'est prévu de pouvoir paramétrer le journal !

**Comment by marienfressinaud** [comment]
Il y a maintenant deux options pour pouvoir configurer ça. Ça se fait au cas par cas par contre pour que le comportement par défaut soit celui d'un espace qui ne se surcharge pas.

Est-ce que ça répond à ton besoin ?

Références :

- https://github.com/flusio/flusio/pull/374
- https://github.com/flusio/flusio/pull/385
- https://pouet.chapril.org/@flus/107326068427570172

**Comment by oncletom** [comment]
Et bien j'avoue que j'ai lutté pour trouver l'emplacement où configurer ce réglage, mais une fois déniché, super !
Je peux lire toutes les weeknotes et certains blogs avec intrêt… et beaucoup de "retard" 🙂 

Merci !

**Comment by marienfressinaud** [comment]
Cool ! Oui je trouve aussi que c’est un poil compliqué à trouver, comme les groupes d'ailleurs, je pense qu'un raffinement des ces options viendra… un jour :)
