### ISSUE TITLE
Export OPML de ses collections Flus

### ISSUE THREAD

**Issue by oncletom** [flusio/flusio#312]
À défaut d'avoir #311, je me disais que j'allais exporter mes collections au format OPML… mais visiblement Flus ne le permet pas ?

![image](https://user-images.githubusercontent.com/138627/126278325-691f305d-6ee3-4ba7-8d2d-9676a076b872.png)

Du coup je me retrouve bloqué dans Flus en mode web, je ne peux pas lire mes abonnements sur un autre logiciel 🙃

**Comment by marienfressinaud** [comment]
C'est prévu assez rapidement ! Note que si tu as besoin, je peux faire une première version en ligne de commande très vite et t'envoyer ton export par email :)

**Comment by oncletom** [comment]
Je peux attendre 👍

**Comment by marienfressinaud** [comment]
Et voilà, c’est bon ! https://flus.fr/carnet/telechargez-vos-donnees.html
