### ISSUE TITLE
Ne prend pas en compte le sous-dossier (APP_PATH)

### ISSUE THREAD

**Issue by locness3** [flusio/flusio#313]
La variable APP_PATH définie dans le fichier .env n'a pas l'air d'être prise en compte : je l'ai configuré pour utiliser /flusio, lorsque j'accède à cette adresse (en ayant proprement configuré le serveur) j'obtiens cette erreur :
```
Minz\Errors\RouteNotFoundError: Path "get /flusio" doesn’t match any route. in /var/www/flusio/lib/Minz/src/Router.php:140
Stack trace:
#0 /var/www/flusio/lib/Minz/src/Engine.php(55): Minz\Router->match()
#1 /var/www/flusio/src/Application.php(89): Minz\Engine->run()
#2 /var/www/flusio/public/index.php(43): flusio\Application->run()
#3 {main}
```

**Comment by marienfressinaud** [comment]
Hello, de ce que j'en vois la variable est bien prise en compte, par contre il est possible que l'application ne fonctionne pas bien ainsi (je n'ai pas l'occasion de tester ça). Pourriez-vous me partager votre configuration que je jette un œil ? (en cachant les infos sensibles s'il y en a)

**Comment by locness3** [comment]
Désolé mais je n'ai plus accès au serveur pour le moment.

**Comment by marienfressinaud** [comment]
Ok ! Je garde le ticket ouvert, je jetterai un œil à l’occasion

**Comment by marienfressinaud** [comment]
Il y avait effectivement un petit bug (le problème des options qu'on n'utilise pas :)) Ça devrait mieux marcher désormais, merci d’avoir remonté le problème !
