### ISSUE TITLE
Comment se connecter au compte par défaut?

### ISSUE THREAD

**Issue by locness3** [flusio/flusio#317]
L'adresse email saisie dans le .env (APP_SUPPORT_EMAIL) est utilisée pour créer un compte utilisateur par défaut.

Comment se connecter à ce compte?  
 Faut-il utiliser "mot de passe oublié" (et donc obligatoirement configurer un serveur smtp)?

**Comment by marienfressinaud** [comment]
Le compte créé n'est pas un compte utilisateur mais un compte système : on n’est pas censé s’y connecter !

**Comment by locness3** [comment]
Ah. Donc si je veux m'inscrire sur mon propre serveur je dois utiliser une email différente de celle de l'admin (moi-même donc)? Pourquoi pas.

**Comment by marienfressinaud** [comment]
L'utilisateur technique n'est pas admin, c’est seulement un utilisateur particulier qui me permet de simplifier certains choix techniques. Comme l'adresse de l'utilisateur technique est utilisée uniquement pour envoyer les messages de support, tu peux utiliser une fausse adresse pour celui-ci.
