### ISSUE TITLE
Dossier de cache non créé par défaut?

### ISSUE THREAD

**Issue by locness3** [flusio/flusio#319]
En laissant la valeur par défaut pour APP_CACHE_PATH, j'ai obtenu une erreur indiquant que le chemin du cache n'existait pas quand j'ai voulu ajouter un lien. Il m'a fallu créer manuellement le dossier ./cache.

Est-ce que j'ai loupé une étape à la configuration, ou s'agit-il d'un bug?

**Comment by marienfressinaud** [comment]
Effectivement, c’est un bug ! Je corrige de suite.

**Comment by marienfressinaud** [comment]
C’est corrigé, merci !
