### ISSUE TITLE
Le défilement est remis en haut après avoir suivi une collection

### ISSUE THREAD

**Issue by Antoine-bdc** [flusio/flusio#378]
Reproduire le problème :
Dans [l'onglet Découvrir](https://app.flus.fr/discovery), faire défiler l'écran et cliquer sur une collection n'étant pas situé en haut du défilement, cliquer sur "suivre", cliquer sur "retour". Alors le défilement est remis tout en haut de la page. 
Cela a également lieu quelque soit l'action que l'on fait au sein de l'écran de la collection. 

Résultat attendu :
Le défilement devrait rester au niveau de la collection que l'on suivait. C'est ce qu'il se passe lorsque l'on ne choisi pas de suivre cette collection ou toute autre action sur la page.

Problème rencontré sur le navigateur smartphone Firefox version 90.1.2 (Build #2015823035). Firefox étant installé sur une téléphone Android 11.

**Comment by marienfressinaud** [comment]
Je ferme ce ticket parce que je manque d’informations et je n’arrive pas à reproduire :

- soit le problème survient avec le bouton "Retour" du navigateur, auquel cas je n’arrive pas à reproduire (le scroll est bien toujours remis au bon endroit de mon côté) et il s’agirait d’un problème navigateur auquel je ne peux pas faire grand-chose
- soit le problème survient avec le bouton "Retour" au sein de l’application, mais le scroll est toujours remis tout en haut de la page (et donc incohérent avec "C'est ce qu'il se passe lorsque l'on ne choisi pas de suivre cette collection ou toute autre action sur la page") et il me semble que c’est un comportement attendu (ça me ferait bizarre que le scroll soit remis au milieu de la page, mais je ne sais pas trop expliquer pourquoi) + ça me semble un poil galère à gérer correctement
