### ISSUE TITLE
[feature-request] possibility to unread a link

### ISSUE THREAD

**Issue by xididri** [flusio/flusio#410]
When a link in bookmarks or collections is marked as read there is no possibility to mark it as unread AFAIK.

It can be marked as read by mistake so it would be useful I think.

**Comment by marienfressinaud** [comment]
I'm not sure I want to add another option to unread a link, I'd like to keep the number of options to the strict minimum. In this case, I can think of two alternatives:

1. you can add the link to your bookmarks so you don't forget it (that's what I do myself)
2. if you really want to remove the "read" status, you can click on "Edit" and "Delete the link" from the "Links read" collection. But don't do this if you added a comment or if it's attached to another collection :)

**Comment by marienfressinaud** [comment]
I could consider to add an option in the "Links read" collection though :thinking:

**Comment by marienfressinaud** [comment]
It's now possible from the read list: https://app.flus.fr/read

Thanks for the suggestion!

**Comment by xididri** [comment]
Thank you very much, I copied the link from my read list, removed it with the new option and added it back to my bookmarks. This is not something that you do often so it's doable.
