### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by fnuttens** [flusio/flusio#500]
Le site ne répond plus 🤕

**Comment by fnuttens** [comment]
L'incident ne semble pas avoir été détecté sur https://status.flus.fr/

**Comment by marienfressinaud** [comment]
Oui j'ai corrigé ce matin en me levant. La base de données a crashé (Out Of Memory). J'ai réduit la taille mémoire qu'elle pouvait prendre mais je n'ai pas le temps aujourd'hui d'annoncer l'incident + comprendre pourquoi status.flus.fr ne l'a pas détecté. Je garde ton ticket ouvert pour me souvenir de le faire :)

**Comment by fnuttens** [comment]
Super, merci pour ta réactivité :)

**Comment by fnuttens** [comment]
On appréciera au passage l'heureux hasard d'être tombé sur la 500ième issue pour ce problème 😄

**Comment by marienfressinaud** [comment]
Oui et non, justement :p Tout le problème de status.flus.fr, c’est que Flus n'a pas renvoyé d’erreur 500 quand la base de données était éteinte, mais elle aurait dû et ça sera corrigé :)

**Comment by marienfressinaud** [comment]
J’ai annoncé l’incident ici : https://status.flus.fr/a/1735812865935750457  
Et j’ai corrigé le bug dans flusio : https://github.com/flusio/flusio/pull/501

Merci de me l’avoir remonté ! :)
