### ISSUE TITLE
Quid d'un flux XML qui ne s'annonce pas comme tel ?

### ISSUE THREAD

**Issue by thom4parisot** [flusio/flusio#533]
J'ai tenté de m'abonner à https://latracebleue.net/index.php?rss=admin et ça n'a pas fonctionné.

Il semblerait que l'entête HTTP ne spécifie pas le bon `Content-Type` mais le _texte_ est parseable.

L'outil ne s'annonce pas, du coup c'est difficile de proposer une piste de résolution à son admin.

🤷🏻

**Comment by marienfressinaud** [comment]
Le content-type est ok (`application/rss+xml`) et le flux est bien reconnu comme tel : https://app.flus.fr/collections/1741963396143483218

Par contre il y a un problème dans la génération du flux : il est annoncé comme encodé en UTF-8, [mais contient des caractères qui ne le sont pas](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flatracebleue.net%2Findex.php%3Frss%3Dadmin) (et d’autres qui le sont, ce qui rend les contournements très compliqués). En l’occurrence je ne peux rien faire ici, c’est la méthode PHP [`DOMDocument::loadXML()`](https://www.php.net/manual/fr/domdocument.loadxml.php) qui m’envoie bouler.

Je n’ai pas compris :

> L'outil ne s'annonce pas

Est-ce que tu voulais dire que Flus n’explique pas l’erreur ?

**Comment by thom4parisot** [comment]
Non pardon, je disais 2 fois la même chose, et je me suis planté : je n'avais pas vu l'annonce du `Content-Type`.

Évidemment, le [document XHTML](view-source:https://latracebleue.net/) est préfixé avec `<?xml version="1.0" encoding="iso-8859-1"?>`… mais pas le flux RSS.

**Comment by marienfressinaud** [comment]
J’ai tenté un contournement en changeant manuellement l'encoding pour de l'iso-8859-1 (cf https://github.com/flusio/flusio/commit/6e9d9152a4d7366a2f0a081c1f46ed85a8ba7de8) et ça marche. Cependant, je ne suis vraiment pas sûr de vouloir merger ça : ça donne du poids à de mauvaises pratiques et, même si le flux fonctionnera dans flusio, il ne fonctionnera pas ailleurs à priori.

Je garde le ticket ouvert quelques jours le temps d'y réfléchir.

**Comment by marienfressinaud** [comment]
Finalement j’ai décidé de gérer ce genre de flux pour plusieurs raisons :

- SimplePie gère déjà le cas (avec son propre parser si j'ai bien compris ?)
- j’ai déjà à gérer des tas de flux invalides (dates non déclarées, mauvais content-type notamment)
- le code pour gérer ça n’est ni très long, ni trop compliqué à comprendre

Par rapport à ma tentative de l’autre jour, j’ai changé de stratégie : je considère que l’encoding déclaré est celui souhaité (ici, de l’UTF-8). Je l’extrait donc, et force un réencodage de la chaîne avec `mb_convert_encoding`, ce qui a pour effet de remplacer les caractères non reconnus par des `?`.

Tout est là : https://github.com/flusio/flusio/pull/543

Je fermerai le ticket quand ce sera en production !

**Comment by marienfressinaud** [comment]
Et c’est bon : https://app.flus.fr/collections/1743615831998658438

**Comment by thom4parisot** [comment]
Super, merci beaucoup :) intéressant de suivre ton cheminement de pensée !
