### ISSUE TITLE
Un lien relatif de type `application/rss+xml` suggère une adresse incorrecte de flux à suivre

### ISSUE THREAD

**Issue by thom4parisot** [flusio/flusio#586]
Pour reproduire le problème : 

1. Je me rends sur `https://www.innovation-pedagogique.fr/auteur12.html`
2. Je copie l'adresse de la page
3. Je me rends sur https://app.flus.fr/links/search
4. Je colle
5. 3 propositions sont faites :
 - ajouter la page en question dans "Read later" ou une collection
 - un flux des articles de la personne (sans titre, sans items)
 - un flux des articles du site (sans titre, sans items)

![image](https://user-images.githubusercontent.com/138627/218282550-34f63bf7-b22f-4a1b-94f7-8c8e134b3a17.png)

Quand je saisis l'URL absolue du flux qui m'intéresse (`https://www.innovation-pedagogique.fr/spip.php?page=backend&id_auteur=12`), tout roule, flus indique bien 10 items.

Il semblerait que le code suivant crée cette erreur : 

```html
<link rel="alternate" type="application/rss+xml" title="Michel Briand" href="spip.php?page=backend&amp;id_auteur=12" />
```

Le contenu du href est concaténé à l'adresse de la page courante, qui est elle même fait référence à un fichier. Du coup, ça coince.

**Comment by marienfressinaud** [comment]
Effectivement, [j’oublie](https://github.com/flusio/flusio/blob/main/lib/SpiderBits/src/Url.php#L64-L70) de virer la dernière partie du path quand je reconstruis l’URL absolue… oups :x J’essaye de corriger ça aujourd'hui ou demain !

**Comment by marienfressinaud** [comment]
C’est corrigé par https://github.com/flusio/flusio/commit/8609c7871ae45a9e04e7529f1feaf3a75be5a00a et mis en prod ! Merci d’avoir remonté le bug :)

**Comment by thom4parisot** [comment]
Yeah, merci à toi 🙂
