### ISSUE TITLE
Flux HAL détecté seulement comme une page web

### ISSUE THREAD

**Issue by thom4parisot** [flusio/flusio#641]
Salut, quand je saisis cette URL[^1] dans le champ de recherche/ajouter, Flus propose de bookmarker la page, alors que je m'attendais aussi à m'abonner au flux. Cette URL est celle d'un flux RSS. Il est proposé dans le [résultat de recherche](https://hal.science/search/index/?q=%2A&rows=30&sort=producedDate_tdate+desc&authIdHal_i=1059633), dans les "..." verticaux en gris très clair au-dessus des résultats).

Est-ce un bug ou une fonctionnalité ?

![image](https://github.com/flusio/flusio/assets/138627/66c7a58c-fc68-43d6-a682-1cc87c6696ed)

[^1]: `https://api.archives-ouvertes.fr/search/hal/?omitHeader=true&wt=rss&q=%2A&sort=producedDate_tdate+desc&fq=NOT+instance_s%3Asfo&fq=NOT+instance_s%3Adumas&fq=NOT+instance_s%3Amemsic&fq=NOT+instance_s%3Ahceres&fq=NOT+%28docType_s%3AHDR+AND+submitType_s%3A%28notice+OR+annex%29%29&fq=NOT+docType_s%3A%28MEM+OR+PRESCONF+OR+MINUTES+OR+NOTE+OR+SYNTHESE+OR+OTHERREPORT+OR+REPACT+OR+BOOKREPORT+OR+ETABTHESE+OR+MEMLIC+OR+CREPORT%29&fq=NOT+status_i%3A111&fq=%7B%21tag%3Dtag0__authIdHal_i%7DauthIdHal_i%3A%28%221059633%22%29&defType=edismax&rows=50`

**Comment by marienfressinaud** [comment]
Hello ! Flus n’affiche pas le flux car il n'arrive pas à le détecter. En effet, il reçoit un résultat en JSON : `{"error":{"msg":"Error. See help : \/docs"}}` :no_mouth: J’ai mis un petit moment à comprendre d’où ça venait, car je récupérais bien le flux dans certaines situations, mais pas dans toutes.

Pour le contexte : avant de traiter/stocker une URL, Flus fait plusieurs opérations dessus, et notamment il la nettoie et la met sous une forme "canonique". Pour encoder des espaces contenues dans une URL, il y a deux possibilités : soit l’encoder avec la chaîne `%20`, soit avec le signe `+`. Or dans ton cas, la moulinette de Flus considère que le `+` est un caractère à part entière, et l’encode lui-même dans le caractère `%2B`. À priori, ce n’est pas un comportement attendu et donc un bug de mon côté.

**Comment by marienfressinaud** [comment]
Je t’ai ajouté le flux à la main ici pour que tu puisses t’y abonner : https://app.flus.fr/collections/1790082705576365992

**Comment by marienfressinaud** [comment]
Pour info j’ai corrigé le bug dans https://github.com/flusio/flusio/pull/642/commits/49c324f802fe94e050c0ab1697892a4152758e8b

Le correctif est déjà en prod :)

Merci pour la remontée !
