### ISSUE TITLE
Unable to setup database

### ISSUE THREAD

**Issue by floviolleau** [flusio/flusio#643]
Hi,

Thanks for this amazing project! I'm trying to self-host flusio but I ran to an issue while doing the DB setup: `sudo -u www-data php cli migrations setup`

```log
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P04]: Duplicate database: 7 ERROR:  database "flusio" already exists in /home/<redacted>/flusio/lib/Minz/src/Database.php:243
Stack trace:
#0 /home/<redacted>/flusio/lib/Minz/src/Database.php(243): PDO->exec()
#1 /home/<redacted>/flusio/lib/Minz/src/Database.php(143): Minz\Database->pdoCall()
#2 /home/<redacted>/flusio/lib/Minz/src/Database.php(325): Minz\Database->exec()
#3 /home/<redacted>/flusio/lib/Minz/src/Migration/Controller.php(132): Minz\Database::create()
#4 /home/<redacted>/flusio/lib/Minz/src/Migration/Controller.php(100): Minz\Migration\Controller->initialize()
#5 [internal function]: Minz\Migration\Controller->setup()
#6 /home/<redacted>/flusio/lib/Minz/src/Response.php(711): Generator->current()
#7 /home/<redacted>/flusio/cli(26): Minz\Response::sendToCli()
#8 {main}
  thrown in /home/<redacted>/flusio/lib/Minz/src/Database.php on line 243
```

If I remove the DB, I have:
```log
PHP Fatal error:  Uncaught Minz\Errors\DatabaseError: An error occured during database initialization: SQLSTATE[08006] [7] FATAL:  database "flusio" does not exist. in /home/<redacted>/flusio/lib/Minz/src/Database.php:70
```

What should I do?

**Comment by marienfressinaud** [comment]
Hi,
Indeed it failed at first because your database already existed (I need to fix that). However, I think the file `data/migrations_version.txt` was created and now Flus expects your database to exist (I don't understand why this happened). You can fix this by removing the file: `rm data/migrations_version.txt`

Let me know if it doesn't work!

**Comment by floviolleau** [comment]
Hi,

Thanks for the quick reply. I don't have the file `data/migrations_version.txt`

The only file I have in data is .keep.

**Comment by marienfressinaud** [comment]
Maybe the Postgres user you're using doesn't have the right to create database? I don't handle this case.

**Comment by floviolleau** [comment]
The user had the right to create databases.
```sql
ALTER USER user_name CREATEDB
```

**Comment by marienfressinaud** [comment]
Ok then, I have no idea of what happened sorry :( At least it works!
