### ISSUE TITLE
[BUG] Feed not working

### ISSUE THREAD

**Issue by floviolleau** [flusio/flusio#647]
Hi,

I wanted to import this feed https://alexsoyes.com/carriere/feed but nothing is imported:
![image](https://github.com/flusio/flusio/assets/5442973/4af50119-4f8e-40dd-b91f-d496a83b5c8f)

Maybe, the website owner has broken his feed format?

Thanks for your investigation time.

**Comment by marienfressinaud** [comment]
The feed is served with a `text/html` content type and flusio doesn't consider it as a feed (not entirely at least). I should try to handle this content type and see if it causes any problem.
